### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by enteryournamehere** [DanielRamosAcosta/aura-sdk#1]
This project looks very cool, though it unfortunately does not support keyboard led control.

As described in the Aura SDK FAQ at https://www.asus.com/campaign/aura/us/SDK.html, Aura SDK also has support for keyboards (and mice), while this project only supports motherboard, GPU and DRAM control. Please see if it is possible to add a controller for keyboards (mice would of course be nice too, though not relevant in my case).

**Comment by DanielRamosAcosta** [comment]
I'll try to support them, but I'm blind here as I dont have any ROG Keybord or mice.
