### ISSUE TITLE
warning: controllerCountMb < 1 & DRAM controller isn't supported

### ISSUE THREAD

**Issue by CodeF0x** [DanielRamosAcosta/aura-sdk#3]
First things first, great job! Thanks for making this possible!

However, when running the example provided in the readme file, I get 
```
warning: controllerCountMb < 1
DRAM controller isn't supported
```

From the gif, it appears that we have the same RAM (because your RAM does also not work), and I'm fine with the RAM not being supported. However, what's about the `controllerCountMb < 1` warning?

Is there something I can do about it? The mainboard is a Z370-F. 

Thanks!

**Comment by DanielRamosAcosta** [comment]
Hello @CodeF0x! Sorry for the late response, but I've been busy these days. That's because the SDK is not able to find any lights controller from the motherboard.

Right now I don't have access to my computer (the one in the GIF) so I cannot make any improvements to this library at the moment.

But, there are several things to improve here. We can migrate into the new [`n-api`](https://nodejs.org/api/n-api.html) for integrating with C++. Also, there is a new version of the SDK out there that we could use. I need to organize my life right now and then I'll take a look into this library.

Thanks you for your comment!

**Comment by CodeF0x** [comment]
Hi @DanielRamosAcosta, thanks for the detailed update!

So I guess I will be waiting. Don't put yourself under pressure, it's not that someone's life depends on this ;).

**Comment by IfnotFr** [comment]
Hi @DanielRamosAcosta 

I have this problem too :(

I tried to :
- Download the lastest AuraSDK and replaced your "AuraSDK" folder by the new one.
- Moved into your project and ran `npm run compile:cpp`

But no luck ... I am not a c/c++ developer so I did not understand what is below the hood sadly ... :(

I may contribute modestly financially if you want to continue working on this :)

**Comment by DanielRamosAcosta** [comment]
Hey @SauceCodeFr. right now Asus has has released version 3 of the SDK as you might have read in the fourm. Right now I'm investigating the best approach to write a new wrapper using the new SDK and the new `n-api`. I want to continue working on this, but don't worry about contributing financially, but thanks!

If you want to help @SauceCodeFr  and @CodeF0x , I would ask you to test the new version of the library when it's released, thanks!

**Comment by IfnotFr** [comment]
Hey @DanielRamosAcosta :)

I hope everything is okay in you life beside this project ! I appreciate your honesty, and I maybe I can contribute to the code side. I spend the last days learning about `n-api` and it looks almost to easy, they made a very very good work with this library, I am excited about all the opportunities of including DLL in node apps !

No problem for helping with testing ! I have a SFF build on a Skyreach with a X570-I with on board leds, 3x 12v leds stripes, 2 x ram adressable leds, 1 x adressable 5v led stripe on cpu fan.

**Comment by DanielRamosAcosta** [comment]
Thanks for your help @SauceCodeFr! Tomorrow I'm going to upload some new code in a branch. I'm going to send you an email to sync up. Thanks!

**Comment by CodeF0x** [comment]
Hi @DanielRamosAcosta, I would be glad to test the new version too once it's released! I'll give you some feedback then.

**Comment by CodeF0x** [comment]
Hello @DanielRamosAcosta! Sorry for the late response, but life got in the way. Thanks for all your effort, but sadly I can't get it even installed properly. 

Checking out the new branch and doing `npm i`, I get the following stacktrace:

```
C:\Users\tobia\Documents\Projekte\aura-sdk>npm i

> aura-sdk@1.0.0 install C:\Users\tobia\Documents\Projekte\aura-sdk
> node-gyp rebuild


C:\Users\tobia\Documents\Projekte\aura-sdk>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  nothing.vcxproj -> C:\Users\tobia\Documents\Projekte\aura-sdk\build\Release\\nothing.lib
  main.cpp
c:\users\tobia\documents\projekte\aura-sdk\cppsrc\samples\aurasdk_x86.tlh(1242): fatal error C1083: File (Include) cannot be opened: "E:\Documentos\Proyectos Personales\Mios\AuraTutorial\AuraTutorial\Debug\AuraSdk_x86.tli": N
o such file or directory [C:\Users\tobia\Documents\Projekte\aura-sdk\build\testaddon.vcxproj]
  AuraSdk.cpp
c:\users\tobia\documents\projekte\aura-sdk\cppsrc\samples\aurasdk_x86.tlh(1242): fatal error C1083: File (Include) cannot be opened: "E:\Documentos\Proyectos Personales\Mios\AuraTutorial\AuraTutorial\Debug\AuraSdk_x86.tli": N
o such file or directory [C:\Users\tobia\Documents\Projekte\aura-sdk\build\testaddon.vcxproj]
  AuraSdkWrapper.cpp
c:\users\tobia\documents\projekte\aura-sdk\cppsrc\samples\aurasdk_x86.tlh(1242): fatal error C1083: File (Include) cannot be opened: "E:\Documentos\Proyectos Personales\Mios\AuraTutorial\AuraTutorial\Debug\AuraSdk_x86.tli": N
o such file or directory [C:\Users\tobia\Documents\Projekte\aura-sdk\build\testaddon.vcxproj]
  win_delay_load_hook.cc
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\tobia\Documents\Projekte\aura-sdk
gyp ERR! node -v v8.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aura-sdk@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aura-sdk@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tobia\AppData\Roaming\npm-cache\_logs\2020-02-15T11_49_55_455Z-debug.log
``` 

Any ideas? Thanks for your all effort!
