### ISSUE TITLE
Lots of build errors...

### ISSUE THREAD

**Issue by DrFizzles** [DanielRamosAcosta/aura-sdk#5]
Hi!

Not sure if anyone still looks at this but I just built a new Aura Sync capable PC and wanted to use this library but I can't get it built. It gives a ton of build errors so I put them in a pastebin.

https://pastebin.com/Lf5KkhJe

I tried installing an older version of Visual Studio and an older version of Python to see if it would help but I just keep getting the same errors.

Any solutions?

**Comment by Garfonso** [comment]
Not sure if it is related, but are you sure that you are using a 32bit node? I had a lot of build errors with 64 bit node, too.

**Comment by Pyragon** [comment]
I am having the same issue. I have confirmed with NVM that I am using the 32bit node.

**Comment by Pyragon** [comment]
https://i.imgur.com/xG2KRWk.png

https://i.imgur.com/zpxwwov.png

**Comment by DrFizzles** [comment]
So I was able to get it working by installing Node 8 (specifically 8.17.0 32bit).

I don't know if you have to go back quite that far, but I found [this issue](https://github.com/bcoin-org/bcrypto/issues/7) on an unrelated repository that listed a few functions that have been deprecated - the exact functions that are throwing errors in the build process. And I kept seeing that those functions aren't working in Node 12 while the issue references Node 8 so I just started with Node 8 and it worked.

If somebody wants to test with newer versions and arches feel free.
